### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by nimoc** [fast-flow/upload.react#2]
https://github.com/fast-flow/upload.react/blob/master/lib/ajaxUpload.js#L98
name 应该去掉

https://github.com/fast-flow/upload.react/blob/master/lib/ajaxUpload.js#L100

测试accept 的浏览器兼容性

https://github.com/fast-flow/upload.react/blob/master/lib/ajaxUpload.js#L49

不通过ms({type: 'onChange'}) 触发，而是 self.onChange(e.target.files)

**Comment by Grifree** [comment]
finish
